apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              value: neo4j/12345678
            - name: NEO4J_apoc_export_file_enabled
              value: "true"
            - name: NEO4J_apoc_import_file_enabled
              value: "true"
            - name: NEO4J_apoc_import_file_use__neo4j__config
              value: "true"
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: my-neo4j-service
spec:
  ports:
    - port: 7687
  selector:
    app: neo4j
